server:
  port: 8080
    
spring:
  application:
    name: PRODUCT-SERVICE

    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/productdb
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    hibernate:
      ddl-auto: update
  config:
     import: configserver:http://localhost:9296
  
  management:
    tracing:
         sampling:
           probability: 1.0     
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}